#+OPTIONS: \n:t

* 202302
** 20230202
twitterの雲行きがいよいよ怪しくなってきたように思う。このままどんどん活動がしにくくなってしまうのだろうか。
……と悲観していてもしょうがない。どうせなら今の活動の仕方であっているのかどうかを、自分で考え直す機会にでもしてみたほうがよいのかもしれない。  
そもそも私はいうほど小説やその他の文章を書いているわけではないから、今使っているプラットホームがなくなったとしても、他の創作者ほどには困らないのかもしれない。  
本当に久しぶりに文章を書いているから、正直何を書けばよいのか何も思いつかない。  
最近、『ずっとやりたかったことを、やりなさい。』という本を読んだ。いつもの創作心構え系の本です。この本を読んで得られるモチベーションがいつまで続くのかはわからない。  
できるだけ長続きせたいとは思っている。これでも、小説を書き続けて生きていきたいと思っている人間ではある。ただ物語を書くというのはなんというか、どうしてこんなに苦痛なのだろうと思うくらい苦痛なことが多い。どのようにすれば書き続けることができるのだろうか。twitterではちょうど「駄作」についての話が流れてきていて、早速炎上しかかっていた。駄作を書いてしまうことは怖い。 
今年の百合文芸には何か書き上げて提出したいと思っている。

** 2023年2月17日
中古のPCを購入した。linuxを導入した。定期的に執筆のガシェットを変更したい衝動に駆られてしまう。あまりよい傾向ではないのだが、またしても衝動に負けてしまった。まあ、何も書かなくなってしまうよりはまだマシではあるのだが……。  
ツイッターを封印したことによってかなり時間を作ることはできたと思う。その時間で何か作品を書くことができたのかというと、そういうわけではないのだが……。  
カクヨムが予定していたコンテストに非常に興味を持っている。賢いヒロインコンテストだったか。自分が一番書きたいキャラクターではあるので、チャレンジしたい。目標として、まずは１作だけでも投稿したいが、５作くらい出したい気持ちもある。だがそれは物理的に難しい。
零合舎さんの百合アンソロジーを読んでいる。非常に面白い。面白いし面白い。つまりfunでありinterstingで、読んでいて精神が受ける刺激が大きい。奇抜な中にテンプレが、テンプレの中に奇抜があり、読者を飽きさせない、それでいて楽しませるだけでは終わらない軸を感じる。今は半分ほどまでしか読めていないので、今はまだ抽象的な感想を言うことしかできない。

** 2023年2月17日
少しだけ執筆環境の整理をした。
テキストエディタのemacsを導入した。
ついでにgithubもまた使えるように調整した。
普通のテキストファイルとは少し違う形で書いているので、改行を表現する方法がずっとなかったのだが、やっと見つかった。
「+OPPTIONS: \n:t」を文頭に書いて.orgから.mdに変換することで、markdown用の改行の表現に書き換えることだできるようだ。
ツイッターを触らずに過ごすことができている。これは快挙かもしれない。
日本語変換の機能がエディタに入っているので、辞書登録をどうすればよいのかわからない。だからツイッターを急に英語に変換できなくなってしまった。
ツイッターをやめて、自分が真っ先にしたことは、他の時間つぶし手段を探すということだった。他にやるべきこととか、本当はやりたい創作活動などをほっぽりだして、最初に選んだ行動がそれだったのだ。はじめはピクシブに手を出そうとした。私は自分の性格をある程度わかっていたので、ピクシブは事前にアンインストールしておいた。ここまではよかったが、今度はユーチューブに逃げてしまった。一応、おすすめ動画やホームは見ないように決めていたのだが、本人の意志に頼ったルールは総じて形骸化するのが落ちだ。完全に遮断できなくとも、障害をいくつか作っておかなければ、人は楽な方楽しい方へと流れてしまう。ユーチューブは課金もしていたのでアンインストールはしたくなかったのだが、泣く泣くアインストールした。プレミアム会員もやめた。そこまでしても、私はやはり、心を無にして眺めておけるサイトをブラウザで探し始める。ここまでくると、ブラウザの使用を完全に止めることはできないので、打つ手がなくなってしまう。ブラウザでツイッターやピクシブ、ユーチューブを見るという行動にはまだ至っていない。
なぜかと考えてみたが、使いにくさという障害が立ちはだかっているというのが大きいだろう。特にピクシブはアプリでなければほぼ使い物にならない（それは言いすぎかもしれないが……）。
面白いことに、ユーチューブについては、一度課金して広告がない状態を知ってしまったためか、広告がある状態でわざわざユーチューブを見たくないという感情が生まれている。一度課金してやはりやめた人は、より強く離れることができるのかもしれない。
もしツイッターをやめたいならば、一度課金して広告を減らして、それからそれをストップすることで反動を利用して断つことができるのではないか。依存症克服の手段の一つを発見してしまったかもしれない。
githubの設定もうまく行った。無事に更新できるようになったようだ。しばらくは色々とできることを増やしていきたいと思う。執筆環境を整えること自体が現実逃避なのではないかという気がしてくるし、実際にそうなのだろうとは思うが、ただ動画やつぶやきを眺めているだけの状態よりはまだマシなのかなと感じる。いや、そうでもないのかもしれない。精神が受ける影響についてより詳細に観察してみる必要があるのかもしれない。
emacs上で使用できるgit、magitの導入を進めている。今はテストとしてこの文章を書いている。

** 2023年2月19日
今週は土日に用事があったので何も文章を書かなかった。
バックアップファイルが大量に生成されるのがかなり煩わしくなってしまったので、バックアプファイルを一箇所にまとめる設定を作ってみた。実際にうまくいっているかはわからないので、この文章を書いたあとで確認して見る予定。
フォルダを確認してみたが、うまくいっていないような気がする。

** 2023年2月20日
タイトルでは2023年2月20日となっているが、実際は2023年2月21日の朝（というより夜中だろうか）に書いている。
月曜日はかなり調子が悪かった。ツイッター・ピクシブ・ユーチューブを封印してから何日が経っただろうか。そろそろ一週間くらいかなという気がする。とはいえ土日の２日間は用事があったため自発的に封印はしていないのでノーカウントとみなしてもよいような気がする。封印したことによる影響がかなり大きく出始めている気がするので書き留めておこうと思う。
まず物理的な面、つまり精神的な面についてはあまり良い影響は出ていない。各種SNSやサービスを禁止したとしても、情報的な刺激を求めて、ブラウザで様々なサイトをめぐることになってしまい、結果としてそこで時間を大量に消費してしまう。あるいは、無為に時間を消費することそのものに自分の身体と精神が依存してしまっているのかもしれない。そうした仮設はさておいても、とにかく良い結果は出ていないということははっきりと言えると思う。この先にどうなるかはわからないが……。
次に精神的な面についてだが、こちらもかなり悪い。非常に疲弊している。外界との繋がりの大部分を失ってしまったことで、閉塞感に襲われている。そうした閉塞感から抜け出したくて、ブラウザを開いてインターネットの中をさまようことになる。そこから何か有益なコンテンツに向かっていくことができればよかったのだが（というよりそれを目指して各種サービスを封印しているのだが）そう目的通りに自分の精神は動いてくれなかった。
情報刺激を求めてネットの世界をさまよった結果、昔閲覧していた2chのまとめやヲチスレなどに引きずり込まれてしまった。あまり質のよい情報ではないし、むしろツイッターなどよりも攻撃的だったり批判的だったりする文章が大量に流れ込んできて、次第に精神が疲弊してしまった。他の情報で感情を上書きしたいが、封印しているサービスは使えないから八方塞がりになってしまう。結局ネットの中に戻るしかない。そんな悪循環を繰り返しているうちに精神も肉体も疲弊して睡眠もままならなくなってしまった。
総合的に見て、かなり悪い状況だ。封印を解いたほうが良いのではないかとも思う。とはいえ封印した時点でも、このまま依存していたら本当に人生がだめになってしまうと思ったから始めたのであり、また元の生活に戻ってしまうというのも嬉しくない。これは一時的な禁断症状のようなものなのではないかと考えている。だから、今の苦しみも一時的なものであって、次第に薄れていくのではないかと思う。禁断症状によってネットの海に沈んでしまうのはまた別の悪い習慣を呼び寄せてしまいそうなので、ネットを徘徊するのもしばらくは禁止したほうがよいのかもしれない。そのためのブラウザの拡張機能の設定や新しいアプリのインストール作業をまたしなければならないのかと思うと少し憂鬱だ。


閉塞感から逃れるために、昔ハマっていたアニメの再視聴している。一定期間、情報の本流から逃れると、これまで見てきたものや読んできたものを振り返ろうとする力が働くのかもしれない。そしてこれは、自分を取り戻しているということなのかもしれない。
実存主義や各種の思想にハマっていった経緯を再度確認した。カクヨムで自分の思想の変遷を振り返る文章を書いていた。あの続きを書いてみたいと思っている。『結城友奈は勇者である』と『艦これ』の二次創作によって自分の実存についてと自分をとりまく社会や共同体のあり方について否応もなく考えさせられることになった。そうした経緯について色々と書いていきたいと思う。



