#+OPTIONS: \n:t ^:nil

* 202302
** 20230202
twitterの雲行きがいよいよ怪しくなってきたように思う。このままどんどん活動がしにくくなってしまうのだろうか。
……と悲観していてもしょうがない。どうせなら今の活動の仕方であっているのかどうかを、自分で考え直す機会にでもしてみたほうがよいのかもしれない。  
そもそも私はいうほど小説やその他の文章を書いているわけではないから、今使っているプラットホームがなくなったとしても、他の創作者ほどには困らないのかもしれない。  
本当に久しぶりに文章を書いているから、正直何を書けばよいのか何も思いつかない。  
最近、『ずっとやりたかったことを、やりなさい。』という本を読んだ。いつもの創作心構え系の本です。この本を読んで得られるモチベーションがいつまで続くのかはわからない。  
できるだけ長続きせたいとは思っている。これでも、小説を書き続けて生きていきたいと思っている人間ではある。ただ物語を書くというのはなんというか、どうしてこんなに苦痛なのだろうと思うくらい苦痛なことが多い。どのようにすれば書き続けることができるのだろうか。twitterではちょうど「駄作」についての話が流れてきていて、早速炎上しかかっていた。駄作を書いてしまうことは怖い。 
今年の百合文芸には何か書き上げて提出したいと思っている。

** 2023年2月17日
中古のPCを購入した。linuxを導入した。定期的に執筆のガシェットを変更したい衝動に駆られてしまう。あまりよい傾向ではないのだが、またしても衝動に負けてしまった。まあ、何も書かなくなってしまうよりはまだマシではあるのだが……。  
ツイッターを封印したことによってかなり時間を作ることはできたと思う。その時間で何か作品を書くことができたのかというと、そういうわけではないのだが……。  
カクヨムが予定していたコンテストに非常に興味を持っている。賢いヒロインコンテストだったか。自分が一番書きたいキャラクターではあるので、チャレンジしたい。目標として、まずは１作だけでも投稿したいが、５作くらい出したい気持ちもある。だがそれは物理的に難しい。
零合舎さんの百合アンソロジーを読んでいる。非常に面白い。面白いし面白い。つまりfunでありinterstingで、読んでいて精神が受ける刺激が大きい。奇抜な中にテンプレが、テンプレの中に奇抜があり、読者を飽きさせない、それでいて楽しませるだけでは終わらない軸を感じる。今は半分ほどまでしか読めていないので、今はまだ抽象的な感想を言うことしかできない。

** 2023年2月17日
少しだけ執筆環境の整理をした。
テキストエディタのemacsを導入した。
ついでにgithubもまた使えるように調整した。
普通のテキストファイルとは少し違う形で書いているので、改行を表現する方法がずっとなかったのだが、やっと見つかった。
「+OPPTIONS: \n:t」を文頭に書いて.orgから.mdに変換することで、markdown用の改行の表現に書き換えることだできるようだ。
ツイッターを触らずに過ごすことができている。これは快挙かもしれない。
日本語変換の機能がエディタに入っているので、辞書登録をどうすればよいのかわからない。だからツイッターを急に英語に変換できなくなってしまった。
ツイッターをやめて、自分が真っ先にしたことは、他の時間つぶし手段を探すということだった。他にやるべきこととか、本当はやりたい創作活動などをほっぽりだして、最初に選んだ行動がそれだったのだ。はじめはピクシブに手を出そうとした。私は自分の性格をある程度わかっていたので、ピクシブは事前にアンインストールしておいた。ここまではよかったが、今度はユーチューブに逃げてしまった。一応、おすすめ動画やホームは見ないように決めていたのだが、本人の意志に頼ったルールは総じて形骸化するのが落ちだ。完全に遮断できなくとも、障害をいくつか作っておかなければ、人は楽な方楽しい方へと流れてしまう。ユーチューブは課金もしていたのでアンインストールはしたくなかったのだが、泣く泣くアインストールした。プレミアム会員もやめた。そこまでしても、私はやはり、心を無にして眺めておけるサイトをブラウザで探し始める。ここまでくると、ブラウザの使用を完全に止めることはできないので、打つ手がなくなってしまう。ブラウザでツイッターやピクシブ、ユーチューブを見るという行動にはまだ至っていない。
なぜかと考えてみたが、使いにくさという障害が立ちはだかっているというのが大きいだろう。特にピクシブはアプリでなければほぼ使い物にならない（それは言いすぎかもしれないが……）。
面白いことに、ユーチューブについては、一度課金して広告がない状態を知ってしまったためか、広告がある状態でわざわざユーチューブを見たくないという感情が生まれている。一度課金してやはりやめた人は、より強く離れることができるのかもしれない。
もしツイッターをやめたいならば、一度課金して広告を減らして、それからそれをストップすることで反動を利用して断つことができるのではないか。依存症克服の手段の一つを発見してしまったかもしれない。
githubの設定もうまく行った。無事に更新できるようになったようだ。しばらくは色々とできることを増やしていきたいと思う。執筆環境を整えること自体が現実逃避なのではないかという気がしてくるし、実際にそうなのだろうとは思うが、ただ動画やつぶやきを眺めているだけの状態よりはまだマシなのかなと感じる。いや、そうでもないのかもしれない。精神が受ける影響についてより詳細に観察してみる必要があるのかもしれない。
emacs上で使用できるgit、magitの導入を進めている。今はテストとしてこの文章を書いている。

** 2023年2月19日
今週は土日に用事があったので何も文章を書かなかった。
バックアップファイルが大量に生成されるのがかなり煩わしくなってしまったので、バックアプファイルを一箇所にまとめる設定を作ってみた。実際にうまくいっているかはわからないので、この文章を書いたあとで確認して見る予定。
フォルダを確認してみたが、うまくいっていないような気がする。

** 2023年2月20日
タイトルでは2023年2月20日となっているが、実際は2023年2月21日の朝（というより夜中だろうか）に書いている。
月曜日はかなり調子が悪かった。ツイッター・ピクシブ・ユーチューブを封印してから何日が経っただろうか。そろそろ一週間くらいかなという気がする。とはいえ土日の２日間は用事があったため自発的に封印はしていないのでノーカウントとみなしてもよいような気がする。封印したことによる影響がかなり大きく出始めている気がするので書き留めておこうと思う。
まず物理的な面、つまり精神的な面についてはあまり良い影響は出ていない。各種SNSやサービスを禁止したとしても、情報的な刺激を求めて、ブラウザで様々なサイトをめぐることになってしまい、結果としてそこで時間を大量に消費してしまう。あるいは、無為に時間を消費することそのものに自分の身体と精神が依存してしまっているのかもしれない。そうした仮設はさておいても、とにかく良い結果は出ていないということははっきりと言えると思う。この先にどうなるかはわからないが……。
次に精神的な面についてだが、こちらもかなり悪い。非常に疲弊している。外界との繋がりの大部分を失ってしまったことで、閉塞感に襲われている。そうした閉塞感から抜け出したくて、ブラウザを開いてインターネットの中をさまようことになる。そこから何か有益なコンテンツに向かっていくことができればよかったのだが（というよりそれを目指して各種サービスを封印しているのだが）そう目的通りに自分の精神は動いてくれなかった。
情報刺激を求めてネットの世界をさまよった結果、昔閲覧していた2chのまとめやヲチスレなどに引きずり込まれてしまった。あまり質のよい情報ではないし、むしろツイッターなどよりも攻撃的だったり批判的だったりする文章が大量に流れ込んできて、次第に精神が疲弊してしまった。他の情報で感情を上書きしたいが、封印しているサービスは使えないから八方塞がりになってしまう。結局ネットの中に戻るしかない。そんな悪循環を繰り返しているうちに精神も肉体も疲弊して睡眠もままならなくなってしまった。
総合的に見て、かなり悪い状況だ。封印を解いたほうが良いのではないかとも思う。とはいえ封印した時点でも、このまま依存していたら本当に人生がだめになってしまうと思ったから始めたのであり、また元の生活に戻ってしまうというのも嬉しくない。これは一時的な禁断症状のようなものなのではないかと考えている。だから、今の苦しみも一時的なものであって、次第に薄れていくのではないかと思う。禁断症状によってネットの海に沈んでしまうのはまた別の悪い習慣を呼び寄せてしまいそうなので、ネットを徘徊するのもしばらくは禁止したほうがよいのかもしれない。そのためのブラウザの拡張機能の設定や新しいアプリのインストール作業をまたしなければならないのかと思うと少し憂鬱だ。


閉塞感から逃れるために、昔ハマっていたアニメの再視聴している。一定期間、情報の本流から逃れると、これまで見てきたものや読んできたものを振り返ろうとする力が働くのかもしれない。そしてこれは、自分を取り戻しているということなのかもしれない。
実存主義や各種の思想にハマっていった経緯を再度確認した。カクヨムで自分の思想の変遷を振り返る文章を書いていた。あの続きを書いてみたいと思っている。『結城友奈は勇者である』と『艦これ』の二次創作によって自分の実存についてと自分をとりまく社会や共同体のあり方について否応もなく考えさせられることになった。そうした経緯について色々と書いていきたいと思う。

** 2023年2月21日
orgファイルの冒頭に書くOPTIONの意味がわかってきた。これを使うことで、export時の挙動をかなり自分好みに制御することができそうだ。
少し読書ができるようになってきた。精神がほんの少しだけ回復してきたようだ。外出することもできるようになってきた。まずは今日早く寝ることから始めよう。
各種SNS封印の影響観察。
結局、禁断症状に負けて一瞬だけユーチューブをインストールして動画を2つ観たり、ツイッターをインストールして検索で話題のトレンドを確認したりしてしまった。結局SNSの封印によって私が何から無意識に逃れようと思っていたのか、そして今回の禁断症状による封印破りはなぜ起こってしまったのかを簡単に記しておいたほうがよいと感じた。
結局、ブラウザでネットを徘徊していたときも、衝動的にツイッターに再ログインしたときも、「他の誰かが何を言っているのだろうか？」という情報を求めていた。これは過去の記憶だが、一年ほど前にもSNSを封印しようとしたときがあり、その際にも禁断症状が起きた。そしてそのときは、アマゾンや読書メーターのレビューをひたすら読んでいた。ユーチューブでは５分から２０分ほどの動画を延々と再生し続けていたことを考えると、「適度に短くコンパクトにまとまった」「他の人の意見」という種類の情報に依存しているのではないかと思う。
再度、禁断衝動が大きくなったときに自分が逃げ込んだものを思い出してみると、2chのまとめ、ヲチスレ、アマゾンレビュー、読書メーター、短いユーチューブ動画、ツイッターの検索欄……等々。
新しい情報、という条件も加えたくなったが、これは意外と関係ないらしい。一度見た意見をもう一度見たりすることが多い。
私は実際、ある程度の長さの情報を受け取ることができなくなりは始めているように感じる。10000字以下の短編小説ですら、最後まで読むことが難しくなっている。24分のアニメを1クール連続で観るといった楽しみ方も途中で挫折してしまう。以前はこんなことではなかったはずだ。だが、100字〜1000字ほどの短い意見が大量に流れていくるフォーマットであれば、逆に2時間でも3時間でも、夜ふかしすらしながら眺め続けることが可能になっている。脳が最適化されてしまっているような気がする。

** 2023年2月23日
今日は昨日よりは読書が進まない。精神状態もあまり良くはない。一日単位で精神状態が上下しているようだ。つまり不安定になっているということだろうか。こうしてPCを開いて文章を打てているだけもまだマシなのかもしれないが。それすらもままならない状態が続いていたことを考えると……。
昨日の時点で、ツイッターの封印を解除した。変わりに、アプリの使用時間に制限をかけた。時間は15分。長いかなと思ったが、その状態でほんの少しだけ（主観）ツイッターを開いて眺めていたらすぐに制限時間に達してしまった。15分があっという間だった。それだけ、実際の使用時間と体感の使用時間が違うのだろう。依存を自覚することじたいが難しい。今日はあまりツイッターに張り付かなかったな、と思っていた日でも、実は一時間位は軽く超えていたのではないだろうかと今では思う。
ツイッターから離れることがそんなに大事なことなのだろうか。そういう疑問も浮かぶ。新しい情報は得られるし、考えるべきテーマもたくさん発掘できる。素敵な創作者の方々と交流することもできる。それでも私はツイッターの負の側面のほうがここ数年は特に強くなっているのではないかと感じている。
ツイッターの情報はトゲトゲしているという表現を以前した。これは少し間違っているのかもしれない。正しくは、ツイッターの情報は私の精神をトゲトゲさせるのかもしれない。私は自分のトゲによって傷ついて疲弊しているような気がする。
私は「これは間違っている！」と判断する瞬間に起こる精神的現象に依存している。同時に「この意見は正しい！」と判断するときの精神的現象にも依存している。どういうことかというと、まず、私は「間違い」を探す。実験用ラットがスイッチを押すかのように、SNSや動画サービスのホームやおすすめを更新し続けていれば簡単に見つけることができる。そしてこの「間違い」に複数寄せられている他の人の「正しい」意見を見て快感のようなものを得ている。このとき私は、「間違い」を見て自分の意見をうんうんと熟考して、それから寄せられている他の人の意見を確認するのではない。そうではなく「間違い」を見た瞬間に私は直感的に不快感を抱く。なぜ不快感を抱くのかを自分で考えるのではなく、私は不快感を抱く理由を寄せられている他の意見から得ようとする。そしてそれが不快感の理由たるものであればその時「正しい」と感じる。このとき、それが本当に正しいのかどうかは関係がない、というより知りようがない。社会的に正しいと言われる意見で「正しい」と感じてその刺激に依存することもあれば、社会的には間違っていると判断されるであろう意見を見て「正しい」と感じてその刺激に依存することもある。これは内容の話ではない。脳内で何が起こっているかの話である。
アマゾンレビューやアニメの感想まとめなどに依存することもある。このことから、上の説明をもう少し広げることができるかもしれない。私は何かを見たとき「直感的な感想」を抱く。それは、感動したとか不快だとか、とにかく言葉で理論的に説明するまえの感想のことだ。この直感的な感想がなぜ起こっているのかについての「説明」を求める。そして、より納得できる説明を求めてひたすらそれを探し続ける。ここで重要なのは、私の中に自分なりの「説明」があり、それとぴったり合うものを探しているわけではないということだ。私は説明を持っていない。持つ前から自分にあう説明を外部に求める。そして私はいつの間にか、自分で説明を用意していなかったことを忘れてしまう。
こうした精神の働きがあるから、SNSは怖いのだ……という話で結論をだそうと思っていたのだが、よく考えると、人は自分で言語化できない感想を抱いてしまったとき、こうした上記のような対応をして救われることがある。あるいはそれこそが「勉強」と呼ばれる行動かもしれないのだ。自分が受け取るすべてのものを自分の力で言語化することなどできない。私は他者の正しいと思える意見を吸収していきながら、少しずつ世界を広げていく。だからそれ自体は悪いことではないのだと思う。人が生きて成長していく限り、つまり世界を広げていく方向性を持っている限り、SNSへの依存を完全になくすことはできないのだと思う。生物が生きるために進化の過程で獲得した性質が、まったく別の病気を呼び込んでしまうのと同じように、SNSへの依存を呼び込んでしまっているのだと思う。

** 2023年2月24日
勇者であるシリーズを、アニメから書籍まで再視聴・再読している。私はやはりこのコンテンツに格別の関心を持っているようだ。二次創作を始めて、一次創作も始めて、色々なことを考えるようになってからしばらくこのコンテンツとは距離を置いていた。正直に傲慢な表現をするなら、もうこの物語から引き出せるものはないと思っていた。だが、良い作品というのは総じて時間が経ってからもう一度観てみると新しい学びを得ることができる。勇者であるシリーズもそうであるようだ。過去の私が未熟だったからなのか、今の私がより混乱した人格になってしまったからなのかはわからないが、それぞれのキャラクターの生き様や世界観から感じ取れるものがより多くなっている気がする。
勇者であるシリーズについて、一度腰を据えて考察してみたいなと思う。世界観についての考察にはあまり興味を感じられない。神道をベースにしているのだろうなということだけはわかるが、文献を漁って元ネタをただ「発見」するだけになってしまうなと虚しい。この物語で私はなぜ感動してしまうのか。この物語が描いている「人」とは何か。「である」という観点からじっくり考えてみたい。
そのための事前訓練として、サルトルの『存在と無』を読んでいる。
