#+OPTIONS: \n:t

* 202302
** 20230202
twitterの雲行きがいよいよ怪しくなってきたように思う。このままどんどん活動がしにくくなってしまうのだろうか。
……と悲観していてもしょうがない。どうせなら今の活動の仕方であっているのかどうかを、自分で考え直す機会にでもしてみたほうがよいのかもしれない。  
そもそも私はいうほど小説やその他の文章を書いているわけではないから、今使っているプラットホームがなくなったとしても、他の創作者ほどには困らないのかもしれない。  
本当に久しぶりに文章を書いているから、正直何を書けばよいのか何も思いつかない。  
最近、『ずっとやりたかったことを、やりなさい。』という本を読んだ。いつもの創作心構え系の本です。この本を読んで得られるモチベーションがいつまで続くのかはわからない。  
できるだけ長続きせたいとは思っている。これでも、小説を書き続けて生きていきたいと思っている人間ではある。ただ物語を書くというのはなんというか、どうしてこんなに苦痛なのだろうと思うくらい苦痛なことが多い。どのようにすれば書き続けることができるのだろうか。twitterではちょうど「駄作」についての話が流れてきていて、早速炎上しかかっていた。駄作を書いてしまうことは怖い。 
今年の百合文芸には何か書き上げて提出したいと思っている。

** 2023年2月17日
中古のPCを購入した。linuxを導入した。定期的に執筆のガシェットを変更したい衝動に駆られてしまう。あまりよい傾向ではないのだが、またしても衝動に負けてしまった。まあ、何も書かなくなってしまうよりはまだマシではあるのだが……。  
ツイッターを封印したことによってかなり時間を作ることはできたと思う。その時間で何か作品を書くことができたのかというと、そういうわけではないのだが……。  
カクヨムが予定していたコンテストに非常に興味を持っている。賢いヒロインコンテストだったか。自分が一番書きたいキャラクターではあるので、チャレンジしたい。目標として、まずは１作だけでも投稿したいが、５作くらい出したい気持ちもある。だがそれは物理的に難しい。
零合舎さんの百合アンソロジーを読んでいる。非常に面白い。面白いし面白い。つまりfunでありinterstingで、読んでいて精神が受ける刺激が大きい。奇抜な中にテンプレが、テンプレの中に奇抜があり、読者を飽きさせない、それでいて楽しませるだけでは終わらない軸を感じる。今は半分ほどまでしか読めていないので、今はまだ抽象的な感想を言うことしかできない。

** 2023年2月17日
少しだけ執筆環境の整理をした。
テキストエディタのemacsを導入した。
ついでにgithubもまた使えるように調整した。
普通のテキストファイルとは少し違う形で書いているので、改行を表現する方法がずっとなかったのだが、やっと見つかった。
「+OPPTIONS: \n:t」を文頭に書いて.orgから.mdに変換することで、markdown用の改行の表現に書き換えることだできるようだ。
ツイッターを触らずに過ごすことができている。これは快挙かもしれない。
日本語変換の機能がエディタに入っているので、辞書登録をどうすればよいのかわからない。だからツイッターを急に英語に変換できなくなってしまった。
ツイッターをやめて、自分が真っ先にしたことは、他の時間つぶし手段を探すということだった。他にやるべきこととか、本当はやりたい創作活動などをほっぽりだして、最初に選んだ行動がそれだったのだ。はじめはピクシブに手を出そうとした。私は自分の性格をある程度わかっていたので、ピクシブは事前にアンインストールしておいた。ここまではよかったが、今度はユーチューブに逃げてしまった。一応、おすすめ動画やホームは見ないように決めていたのだが、本人の意志に頼ったルールは総じて形骸化するのが落ちだ。完全に遮断できなくとも、障害をいくつか作っておかなければ、人は楽な方楽しい方へと流れてしまう。ユーチューブは課金もしていたのでアンインストールはしたくなかったのだが、泣く泣くアインストールした。プレミアム会員もやめた。そこまでしても、私はやはり、心を無にして眺めておけるサイトをブラウザで探し始める。ここまでくると、ブラウザの使用を完全に止めることはできないので、打つ手がなくなってしまう。ブラウザでツイッターやピクシブ、ユーチューブを見るという行動にはまだ至っていない。
なぜかと考えてみたが、使いにくさという障害が立ちはだかっているというのが大きいだろう。特にピクシブはアプリでなければほぼ使い物にならない（それは言いすぎかもしれないが……）。
面白いことに、ユーチューブについては、一度課金して広告がない状態を知ってしまったためか、広告がある状態でわざわざユーチューブを見たくないという感情が生まれている。一度課金してやはりやめた人は、より強く離れることができるのかもしれない。
もしツイッターをやめたいならば、一度課金して広告を減らして、それからそれをストップすることで反動を利用して断つことができるのではないか。依存症克服の手段の一つを発見してしまったかもしれない。
